language: c
sudo: false
script: make
addons:
    apt:
        packages:
            - libconfuse-dev
            - libyajl-dev
            - libasound2-dev
            - libiw-dev
            - libnotify-dev
            - libmpdclient-dev
            - libcap2-bin 
            - asciidoc 
